### PR TITLE
Fix: vue2.7 ShallowMount Composition API TS Error

### LINKED ISSUE #1993: mount and shallowMount do not type check with vue 2.7.x
### Subject of the issue

type checking when using vue-utils when using vue 2.7.8 fails because an extra argument was added to the vue types

```
node_modules/@vue/test-utils/types/index.d.ts:193:80 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@vue/test-utils/types/index.d.ts:193:170 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@vue/test-utils/types/index.d.ts:197:97 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

197 export declare function shallowMount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@vue/test-utils/types/index.d.ts:197:197 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

197 export declare function shallowMount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce

in this repo upgrade `vue`, `vue-template-compiler` and `typescript` (needed to parse the vue d.ts files) then `yarn test:types`

### Expected behaviour

should be compatible

### Actual behaviour

```
❯ yarn test:types
yarn run v1.22.19
$ tsc -p packages/test-utils/types && tsc -p packages/server-test-utils/types
packages/test-utils/types/index.d.ts:191:90 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

191 export declare function mount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:191:183 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

191 export declare function mount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:193:80 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:193:170 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

193 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                                                                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:197:97 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

197 export declare function shallowMount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:197:197 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

197 export declare function shallowMount<V extends Vue, Data, Methods, Computed, Props> (component: ExtendedVue<V, Data, Methods, Computed, Props>, options?: ThisTypedShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, Data, Methods, Computed, Props> & Vue>
                                                                                                                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:199:87 - error TS2314: Generic type 'ExtendedVue' requires 6 type argument(s).

199 export declare function shallowMount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/index.d.ts:199:184 - error TS2314: Generic type 'CombinedVueInstance' requires 6 type argument(s).

199 export declare function shallowMount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentShallowMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                                                                                                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

packages/test-utils/types/test/mount.ts:86:10 - error TS2339: Property 'bar' does not exist on type 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>'.

86     this.bar
            ~~~

packages/test-utils/types/test/shallow.ts:77:10 - error TS2339: Property 'bar' does not exist on type 'Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>'.

77     this.bar
            ~~~


Found 10 errors in 3 files.
```

### Possible Solution

some changes to support latest vue 2

### LINKED ISSUE #2026: Type-checking fails with Vue 2.7.9+
### Subject of the issue

After updating `vue` to 2.7.9 or above, `vue-tsc` throws an type error on the `mount()` call.

Seems triggered by https://github.com/vuejs/vue/pull/12727/files

### Steps to reproduce

```
pnpm create vue@2 --typescript --vitest vue2-test-utils-type-checking
cd vue2-test-utils-type-checking
pnpm i
pnpm type-check
```

### Expected behaviour

The type-checking should succeed without errors.

### Actual behaviour

```
src/components/__tests__/HelloWorld.spec.ts:8:27 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type 'ComponentPublicInstanceConstructor<Vue3Instance<{}, Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ msg: string; }>>>, Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ msg: string; }>>>, {}, {}, true, ComponentOptionsBase<...>> & ... 4 more ... & Readonly<...>, ... 4 more ..., MethodOptions> & Com...' is not assignable to parameter of type 'ExtendedVue<Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<Record<string, any>, Record<string, any>, never, never, ...>>, ... 6 more ..., ComponentOptionsMixin>'.
      Type 'ComponentPublicInstanceConstructor<Vue3Instance<{}, Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ msg: string; }>>>, Readonly<ExtractPropTypes<__VLS_TypePropsToRuntimeProps<{ msg: string; }>>>, {}, {}, true, ComponentOptionsBase<...>> & ... 4 more ... & Readonly<...>, ... 4 more ..., MethodOptions> & Com...' is missing the following properties from type 'VueConstructor<ExtractComputedReturns<{}> & DefaultProps & Vue<Record<string, any>, Record<string, any>, never, never, (event: string, ...args: any[]) => Vue<...>> & ShallowUnwrapRef<...> & Vue<...>>': extend, nextTick, set, delete, and 10 more.

8     const wrapper = mount(HelloWorld, { propsData: { msg: 'Hello Vitest' } })
                            ~~~~~~~~~~

  node_modules/.pnpm/@vue+test-utils@1.3.3_2s2ymob7v2oigx3hqbmnjuqthq/node_modules/@vue/test-utils/types/index.d.ts:195:25
    195 export declare function mount<V extends Vue, Props = DefaultProps> (component: ExtendedVue<V, {}, {}, {}, Props>, options?: FunctionalComponentMountOptions<V>): Wrapper<CombinedVueInstance<V, {}, {}, {}, Props> & Vue>
                                ~~~~~
    The last overload is declared here.


Found 1 error in src/components/__tests__/HelloWorld.spec.ts:8
```

### Possible Solution

I don't know…

### PR DESCRIPTION
**Pull request by mathiash98**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuejs/vue-test-utils/blob/dev/.github/CONTRIBUTING.md#development-setup
- [x] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

Closes #1999 
Fixes #1993 
Fixes #2026

### CODE REVIEW

**Comment by mathiash98** [comment]
CircleCI works fine, seems like the netlify deploy script needs to update its node version from 10 to something more LTS

**Review by haoqunjiang — APPROVED** [review]

**Review by haoqunjiang — COMMENTED** [review]
Wait… This PR doesn't fix https://github.com/vuejs/vue-test-utils/issues/2026

**Comment by mathiash98** [comment]
> Wait… This PR doesn't fix #2026

Hmm could you add the code for a test that fails and I'll add it to the branch to see if it works or not

**Comment by mathiash98** [comment]
Not sure if this PR actually solves anything, anyhow I was able to run Vue 2.7 with jest 27 with following package.json:

```Json
{
"dependencies": {
    "@popperjs/core": "^2.11.6",
    "core-js": "^3.26.1",
    "lodash": "4.17.21",
    "v-tooltip": "2.1.3",
    "vue": "~2.7.14",
    "vue-router": "3.4.3",
    "vue2-leaflet": "2.7.1",
    "vuex": "3.5.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.5",
    "@types/jest": "^29.2.2",
    "@types/lodash": "4.14.188",
    "@typescript-eslint/eslint-plugin": "5.5.0",
    "@typescript-eslint/parser": "5.5.0",
    "@vue/cli-plugin-babel": "^5.0.8",
    "@vue/cli-plugin-eslint": "^5.0.8",
    "@vue/cli-plugin-pwa": "^5.0.8",
    "@vue/cli-plugin-router": "^5.0.8",
    "@vue/cli-plugin-typescript": "^5.0.8",
    "@vue/cli-plugin-unit-jest": "^5.0.8",
    "@vue/cli-plugin-vuex": "^5.0.8",
    "@vue/cli-service": "^5.0.8",
    "@vue/eslint-config-typescript": "7.0.0",
    "@vue/test-utils": "1.3.3",
    "@vue/vue2-jest": "^27.0.0",
    "babel-jest": "^27.5.1",
    "eslint": "7.32.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-vue": "8.1.1",
    "flush-promises": "^1.0.2",
    "jest": "^27.1.5",
    "jest-junit": "15.0.0",
    "prettier": "2.1.2",
    "ts-jest": "^27.1.5",
    "typescript": "4.4.2",
    "vue-template-compiler": "^2.7.14"
  }
}
```


By setting `vue-shims.d.ts` to: 
```TS
/**
 * Extends interfaces in Vue.js
 */

import Vue, { ComponentOptions } from "vue";
import { Store } from "./index";

declare module "vue/types/options" {
  interface ComponentOptions<V extends Vue> {
    store?: Store<any>;
  }
}

declare module "vue/types/vue" {
  interface Vue {
    $store: Store<any>;
  }
}
``` 

For some reason all the type errors come when I remove `declare module "vue/types/vue" (...)`...

**Comment by malykhinvi** [comment]
I managed to fix TS errors with the following type shim:
```ts
declare global {
  // With vue@2.7, DefineComponent is not considered a valid argument for mount and shallowMount
  declare module '@vue/test-utils' {
    import type Vue from 'vue'
    import type { Component } from 'vue'
    import type { ThisTypedShallowMountOptions, ThisTypedMountOptions } from '@vue/test-utils'

    export declare function shallowMount<C extends Component>(
      component: C,
      options?: ThisTypedShallowMountOptions<Vue>
    ): Wrapper<Vue>

    export declare function mount<C extends Component>(
      component: C,
      options?: ThisTypedMountOptions<Vue>
    ): Wrapper<Vue>
  }
}

```

**Comment by lmiller1990** [comment]
Hi, sorry I did not look at this PR for a long time.

Do we still need this? It is just address typing issues?

TS is quite problematic in this library now we also need to support `<script setup>`.

**Comment by mathiash98** [comment]
> Hi, sorry I did not look at this PR for a long time.
> 
> Do we still need this? It is just address typing issues?
> 
> TS is quite problematic in this library now we also need to support `<script setup>`.

We can probably close it, as we have a workaround. At least for my case we will at some point migrate to Vue3 either way

**Comment by lmiller1990** [comment]
Vue 3 is great. I'm still working on cleaning up this repo and patching it, but at a lowered priority.

**Comment by ColinRosati** [comment]
I would say both shim solutions are not valid. Can we re-open this issue?

https://github.com/vuejs/vue-test-utils/pull/2031#issuecomment-1332198764
Solution creates type issues importing components which are commonly declared via shim-vue.d.ts

https://github.com/vuejs/vue-test-utils/pull/2031#issuecomment-1333455266 
This doesnt work if you are using more then just mount, and shallowMount. This overwrites all other declerations.

Vue 2.7 is still being developed as the vue migration path is challenging especially with nuxt projects. 

Extending shallowMount & mount with defineComponent is still needed!

**Comment by ColinRosati** [comment]
[lmiller1990](https://github.com/lmiller1990) RE: https://github.com/vuejs/vue-test-utils/pull/2031#issuecomment-1386253924

Can you point out the <script setup> issue and which version TS makes incompatiblity?

**Comment by lmiller1990** [comment]
Happy to accept a PR improving the types - I don't know the status of Vue 2.7 + script setup + TypeScript + this library - all my Vue 2 projects are written using JS.

What's the feature request exactly?
