### ISSUE TITLE
TypeError: undefined is not a function (evaluating 'Object.entries(modifiers)')

### ISSUE THREAD

**Issue by LuisaAPF** [vuejs/vue-test-utils#1838]
### Subject of the issue

Error when running tests after upgrading from 1.1.3 to 1.1.4. The same errors are seen when trying to upgrade to 1.2.0.
```
02 05 2021 18:28:20.529:INFO [karma-server]: Karma v5.2.3 server started at http://localhost:9876/
02 05 2021 18:28:20.530:INFO [launcher]: Launching browsers PhantomJS with concurrency unlimited
02 05 2021 18:28:20.551:INFO [launcher]: Starting browser PhantomJS
02 05 2021 18:28:21.578:INFO [PhantomJS 2.1.1 (Linux x86_64)]: Connected on socket qWaI9JOTISHjj4hrAAAA with id 58670807
PhantomJS 2.1.1 (Linux x86_64) ERROR
  TypeError: undefined is not a function (evaluating 'Object.entries(modifiers)')
  at webpack:///node_modules/@vue/test-utils/dist/vue-test-utils.js:10313:1 <- index.js:44703
```

### Steps to reproduce

The error is seen when running tests using PhantomJS. The error is not observed on another project that uses ChromeHeadless.
